<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>ReportExpert.Reporting.Expressions</RootNamespace>
    <AssemblyName>ReportExpert.Reporting.Expressions</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ReportExpert.Core\ReportExpert.Core.csproj" />
  </ItemGroup>
</Project>
