// Auto-derived from Microsoft.ReportDesigner.SR Color_* resources (display names).
namespace ReportExpert.RdlcDesigner.Properties;

/// <summary>Named colors offered by the VS RDLC Report Designer color picker.</summary>
public static class ReportColorCatalog
{
    public readonly record struct Entry(string Value, string DisplayName);

    public static IReadOnlyList<Entry> Colors { get; } =
    [
        new("AliceBlue", "Alice Blue"),
        new("AntiqueWhite", "Antique White"),
        new("Aqua", "Aqua"),
        new("Aquamarine", "Aquamarine"),
        new("Azure", "Azure"),
        new("Beige", "Beige"),
        new("Bisque", "Bisque"),
        new("Black", "Black"),
        new("BlanchedAlmond", "Blanched Almond"),
        new("Blue", "Blue"),
        new("BlueViolet", "Blue Violet"),
        new("Brown", "Brown"),
        new("BurlyWood", "Burly Wood"),
        new("CadetBlue", "Cadet Blue"),
        new("Chartreuse", "Chartreuse"),
        new("Chocolate", "Chocolate"),
        new("Coral", "Coral"),
        new("CornflowerBlue", "Cornflower Blue"),
        new("Cornsilk", "Cornsilk"),
        new("Crimson", "Crimson"),
        new("Cyan", "Cyan"),
        new("DarkBlue", "Dark Blue"),
        new("DarkCyan", "Dark Cyan"),
        new("DarkGoldenrod", "Dark Goldenrod"),
        new("DarkGray", "Dark Gray"),
        new("DarkGreen", "Dark Green"),
        new("DarkKhaki", "Dark Khaki"),
        new("DarkMagenta", "Dark Magenta"),
        new("DarkOliveGreen", "Dark Olive Green"),
        new("DarkOrange", "Dark Orange"),
        new("DarkOrchid", "Dark Orchid"),
        new("DarkRed", "Dark Red"),
        new("DarkSalmon", "Dark Salmon"),
        new("DarkSeaGreen", "Dark Sea Green"),
        new("DarkSlateBlue", "Dark Slate Blue"),
        new("DarkSlateGray", "Dark Slate Gray"),
        new("DarkTurquoise", "Dark Turquoise"),
        new("DarkViolet", "Dark Violet"),
        new("DeepPink", "Deep Pink"),
        new("DeepSkyBlue", "Deep Sky Blue"),
        new("DimGray", "Dim Gray"),
        new("DodgerBlue", "Dodger Blue"),
        new("Firebrick", "Firebrick"),
        new("FloralWhite", "Floral White"),
        new("ForestGreen", "Forest Green"),
        new("Fuchsia", "Fuchsia"),
        new("Gainsboro", "Gainsboro"),
        new("GhostWhite", "Ghost White"),
        new("Gold", "Gold"),
        new("Goldenrod", "Goldenrod"),
        new("Gray", "Gray"),
        new("Green", "Green"),
        new("GreenYellow", "Green Yellow"),
        new("Honeydew", "Honeydew"),
        new("HotPink", "Hot Pink"),
        new("IndianRed", "Indian Red"),
        new("Indigo", "Indigo"),
        new("Ivory", "Ivory"),
        new("Khaki", "Khaki"),
        new("Lavender", "Lavender"),
        new("LavenderBlush", "Lavender Blush"),
        new("LawnGreen", "Lawn Green"),
        new("LemonChiffon", "Lemon Chiffon"),
        new("LightBlue", "Light Blue"),
        new("LightCoral", "Light Coral"),
        new("LightCyan", "Light Cyan"),
        new("LightGoldenrodYellow", "Light Goldenrod Yellow"),
        new("LightGray", "Light Gray"),
        new("LightGreen", "Light Green"),
        new("LightPink", "Light Pink"),
        new("LightSalmon", "Light Salmon"),
        new("LightSeaGreen", "Light Sea Green"),
        new("LightSkyBlue", "Light Sky Blue"),
        new("LightSlateGray", "Light Slate Gray"),
        new("LightSteelBlue", "Light Steel Blue"),
        new("LightYellow", "Light Yellow"),
        new("Lime", "Lime"),
        new("LimeGreen", "Lime Green"),
        new("Magenta", "Magenta"),
        new("Maroon", "Maroon"),
        new("MediumAquamarine", "Medium Aquamarine"),
        new("MediumBlue", "Medium Blue"),
        new("MediumOrchid", "Medium Orchid"),
        new("MediumPurple", "Medium Purple"),
        new("MediumSeaGreen", "Medium Sea Green"),
        new("MediumSlateBlue", "Medium Slate Blue"),
        new("MediumSpringGreen", "Medium Spring Green"),
        new("MediumTurquoise", "Medium Turquoise"),
        new("MediumVioletRed", "Medium Violet Red"),
        new("MidnightBlue", "Midnight Blue"),
        new("MintCream", "Mint Cream"),
        new("MistyRose", "Misty Rose"),
        new("Moccasin", "Moccasin"),
        new("NavajoWhite", "Navajo White"),
        new("Navy", "Navy"),
        new("OldLace", "Old Lace"),
        new("Olive", "Olive"),
        new("OliveDrab", "Olive Drab"),
        new("Orange", "Orange"),
        new("OrangeRed", "Orange Red"),
        new("Orchid", "Orchid"),
        new("PaleGoldenrod", "Pale Goldenrod"),
        new("PaleGreen", "Pale Green"),
        new("PaleTurquoise", "Pale Turquoise"),
        new("PaleVioletRed", "Pale Violet Red"),
        new("PapayaWhip", "Papaya Whip"),
        new("PeachPuff", "Peach Puff"),
        new("Peru", "Peru"),
        new("Pink", "Pink"),
        new("Plum", "Plum"),
        new("PowderBlue", "Powder Blue"),
        new("Purple", "Purple"),
        new("Red", "Red"),
        new("RosyBrown", "Rosy Brown"),
        new("RoyalBlue", "Royal Blue"),
        new("SaddleBrown", "Saddle Brown"),
        new("Salmon", "Salmon"),
        new("SandyBrown", "Sandy Brown"),
        new("SeaGreen", "Sea Green"),
        new("SeaShell", "Sea Shell"),
        new("Sienna", "Sienna"),
        new("Silver", "Silver"),
        new("SkyBlue", "Sky Blue"),
        new("SlateBlue", "Slate Blue"),
        new("SlateGray", "Slate Gray"),
        new("Snow", "Snow"),
        new("SpringGreen", "Spring Green"),
        new("SteelBlue", "Steel Blue"),
        new("Tan", "Tan"),
        new("Teal", "Teal"),
        new("Thistle", "Thistle"),
        new("Tomato", "Tomato"),
        new("Turquoise", "Turquoise"),
        new("Violet", "Violet"),
        new("Wheat", "Wheat"),
        new("White", "White"),
        new("WhiteSmoke", "White Smoke"),
        new("Yellow", "Yellow"),
        new("YellowGreen", "Yellow Green"),
    ];

    public static IReadOnlyList<Entry> WithDefaults { get; } =
    [
        new("", "Default"),
        ..Colors
    ];
}
